### ISSUE TITLE
Add more labs for updated content

### ISSUE THREAD

**Issue by lazyfrosch** [NETWAYS/workshop-icinga-director#5]
See [content/trainer/content.md](content/trainer/content.md)

Planned labs:

- [ ] **Lab:** Create a separate disk check to monitor /home on master
- [ ] **Lab:** Add a host for github.com and manually add the serviceset to it
- [ ] **Lab:** Override disk thresholds on master
- [ ] **Lab:** Add partitions field to hosts and build apply for for it

**Comment by martialblog** [comment]
Project archived. Since the workshop was merged with the Icinga Training
